using System;
using System.Threading;
using System.Threading.Tasks;

using Skybeam;
using Skybeam.Abstractions;

// <auto-generated/>
namespace PipelineNamespacePlaceholder.Skybeam.Tests.Snapshots.OneBehavior;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Skybeam", "%VERSION%")]
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]
public class BarHandlerPipeline(IServiceProvider provider)
    : IRequestHandler<
        global::Skybeam.Tests.Snapshots.OneBehavior.Alpha,
        global::Skybeam.Tests.Snapshots.OneBehavior.Omega>
{
    public Task<global::Skybeam.Tests.Snapshots.OneBehavior.Omega> HandleAsync(
        global::Skybeam.Tests.Snapshots.OneBehavior.Alpha input,
        CancellationToken ct = default)
    {
        return PipelineBuilder.Decorate<
            global::Skybeam.Tests.Snapshots.OneBehavior.BarHandler,
            global::Skybeam.Tests.Snapshots.OneBehavior.Alpha,
            global::Skybeam.Tests.Snapshots.OneBehavior.Omega
        >(provider, input, ct)();
    }
}