using System;
using Microsoft.Extensions.DependencyInjection;
using Skybeam.Abstractions;
using Skybeam;

// <auto-generated/>
namespace SnapshotNamespacePlaceholder.CompositeHandler;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Skybeam", "%VERSION%")]
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]

public class PipelineRegistry : IPipelineRegistry
{
    public void Apply(IServiceCollection services)
    {
        services.ReplaceWithPipeline<
            IRequestHandler<
                global::Skybeam.Tests.Snapshots.CompositeHandler.Alpha,
                global::Skybeam.Tests.Snapshots.CompositeHandler.Omega>,
            global::Skybeam.Tests.Snapshots.CompositeHandler.BarHandler,
            global::FancyGlobalPrefix.Skybeam.Tests.Snapshots.CompositeHandler.BarHandlerPipeline>();
        
        services.ReplaceWithPipeline<
            IRequestHandler<
                global::Skybeam.Tests.Snapshots.CompositeHandler.Beta,
                global::Skybeam.Tests.Snapshots.CompositeHandler.Omega>,
            global::Skybeam.Tests.Snapshots.CompositeHandler.BarHandler,
            global::FancyGlobalPrefix.Skybeam.Tests.Snapshots.CompositeHandler.BarHandlerPipeline_1>();
    }
}
