using System;
using System.Threading;
using System.Threading.Tasks;

using Skybeam;
using Skybeam.Abstractions;

// <auto-generated/>
namespace FancyGlobalPrefix.Skybeam.Tests.Snapshots.CompositeHandler;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Skybeam", "0.1.0.0")]
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]
public class BarHandlerPipeline_1(IServiceProvider provider)
    : IRequestHandler<
        global::Skybeam.Tests.Snapshots.CompositeHandler.Beta,
        global::Skybeam.Tests.Snapshots.CompositeHandler.Omega>
{
    public Task<global::Skybeam.Tests.Snapshots.CompositeHandler.Omega> HandleAsync(
        global::Skybeam.Tests.Snapshots.CompositeHandler.Beta input,
        CancellationToken ct = default)
    {
        return PipelineBuilder.Decorate<
            global::Skybeam.Tests.Snapshots.CompositeHandler.BarHandler,
            global::Skybeam.Tests.Snapshots.CompositeHandler.Beta,
            global::Skybeam.Tests.Snapshots.CompositeHandler.Omega
        >(provider, input, ct)();
    }
}