using System;
using Microsoft.Extensions.DependencyInjection;
using Skybeam.Abstractions;
using Skybeam;

// <auto-generated/>
namespace RegistryNamespacePlaceholder.NoBehaviors;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Skybeam", "%VERSION%")]
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]

public class PipelineRegistry : IPipelineRegistry
{
    public void Apply(IServiceCollection services)
    {
        services.ReplaceWithPipeline<
            IRequestHandler<
                global::Skybeam.Tests.Snapshots.NoBehaviors.Alpha,
                global::Skybeam.Tests.Snapshots.NoBehaviors.Omega>,
            global::Skybeam.Tests.Snapshots.NoBehaviors.BarHandler,
            global::PipelineNamespacePlaceholder.Skybeam.Tests.Snapshots.NoBehaviors.BarHandlerPipeline>();
    }
}
