using System.Collections.Generic;
using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Skybeam;

public record HandlerDescription(
    string Name,
    string FullName,
    string ContainingNamespace,
    string InputFullName,
    string OutputFullName,
    string PipelineSuffix = "");

public record BehaviorDescription(string FullNamePrefix);

public record PipelineDescription(
    HandlerDescription HandlerDescription,
    string FullName);

public static class PipelineTextEmitter
{
    public static readonly AssemblyName EmitterAssemblyName = typeof(PipelineTextEmitter).Assembly.GetName();
    public const string NamespacePrefix = "FancyGlobalPrefix";

    public static (SourceText text, PipelineDescription pd) CreateSourceText(
        HandlerDescription handler,
        IReadOnlyList<BehaviorDescription> behaviors)
    {
        // operating over type names everywhere
        string inputType = handler.InputFullName;
        string outputType = handler.OutputFullName;
        string handlerType = handler.FullName;

        string pipelineNamespace = $"{NamespacePrefix}.{handler.ContainingNamespace}";
        string pipelineType = $"{handler.Name}Pipeline{handler.PipelineSuffix}";
        string targetFunc = "original";
        string interfaceType = "InterfaceAlias";
        string delegateType = "DelegateAlias";

        PipelineDescription pd = new
        (
            HandlerDescription: handler,
            FullName: $"global::{pipelineNamespace}.{pipelineType}"
        );

        var sb = new StringBuilder(256);
        sb.AppendLine(
            $$"""
              using System;
              using System.Threading;
              using System.Threading.Tasks;
              using Microsoft.Extensions.DependencyInjection;

              using Skybeam.Abstractions;

              // <auto-generated
              namespace {{pipelineNamespace}};

              using {{interfaceType}} = IRequestHandler<
                  {{inputType}},
                  {{outputType}}>;

              using {{delegateType}} = RequestHandlerDelegate<
                  {{outputType}}>;

              [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{EmitterAssemblyName.Name}}", "{{EmitterAssemblyName.Version}}")]
              [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]

              public class {{pipelineType}}(IServiceProvider provider) : {{interfaceType}}
              {
                  public Task<{{outputType}}> HandleAsync(
                      {{inputType}} input,
                      CancellationToken ct = default)
                  {
                      var handler = provider.GetRequiredService<
                          {{handlerType}}>(); 

                      {{delegateType}} {{targetFunc}} = () => handler.HandleAsync(input, ct);

              """);

        for (int i = 0; i < behaviors.Count; i++)
        {
            string currentFunc = $"f{i}";
            string currentBehavior = $"b{i}";
            string name = behaviors[i].FullNamePrefix;

            sb.AppendLine(
                $"""
                         var {currentBehavior} = provider.GetRequiredService<
                             {name}<
                                 {inputType},
                                 {outputType}>>();

                         {delegateType} {currentFunc} = () => {currentBehavior}.HandleAsync(input, {targetFunc}, ct);

                 """);

            targetFunc = currentFunc;
        }

        sb.Append(
             $$"""
                      return {{targetFunc}}();
                  }
              }
              """);
        SourceText text = SourceText.From(sb.ToString(), Encoding.UTF8);

        return (text, pd);
    }
}
