using System;
using Microsoft.Extensions.DependencyInjection;
using Skybeam.Abstractions;
using Skybeam;

// <auto-generated/>
namespace RegistryNamespacePlaceholder.SameName;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Skybeam", "%VERSION%")]
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]

public class PipelineRegistry : IPipelineRegistry
{
    public void Apply(IServiceCollection services)
    {
        services.ReplaceWithPipeline<
            IRequestHandler<
                global::Skybeam.Tests.Snapshots.SameName.RequestNamespace.Foo,
                global::Skybeam.Tests.Snapshots.SameName.ResponseNamespace.Foo>,
            global::Skybeam.Tests.Snapshots.SameName.HandlerNamespace.Foo,
            global::PipelineNamespacePlaceholder.Skybeam.Tests.Snapshots.SameName.HandlerNamespace.FooPipeline>();
    }
}
