using System;
using System.Threading;
using System.Threading.Tasks;

using Skybeam;
using Skybeam.Abstractions;

// <auto-generated/>
namespace FancyGlobalPrefix.Skybeam.Tests.Snapshots.SameName.HandlerNamespace;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Skybeam", "0.1.0.0")]
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]
public class FooPipeline(IServiceProvider provider)
    : IRequestHandler<
        global::Skybeam.Tests.Snapshots.SameName.RequestNamespace.Foo,
        global::Skybeam.Tests.Snapshots.SameName.ResponseNamespace.Foo>
{
    public Task<global::Skybeam.Tests.Snapshots.SameName.ResponseNamespace.Foo> HandleAsync(
        global::Skybeam.Tests.Snapshots.SameName.RequestNamespace.Foo input,
        CancellationToken ct = default)
    {
        return PipelineBuilder.Decorate<
            global::Skybeam.Tests.Snapshots.SameName.HandlerNamespace.Foo,
            global::Skybeam.Tests.Snapshots.SameName.RequestNamespace.Foo,
            global::Skybeam.Tests.Snapshots.SameName.ResponseNamespace.Foo
        >(provider, input, ct)();
    }
}