using System;
using Microsoft.Extensions.DependencyInjection;
using Skybeam.Abstractions;
using Skybeam;

// <auto-generated/>
namespace Tests.TwoBehaviors;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Skybeam", "%VERSION%")]
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]

public class PipelineRegistry : IPipelineRegistry
{
    public void Apply(IServiceCollection services)
    {
        services.ReplaceWithPipeline<
            IRequestHandler<
                global::Skybeam.Tests.Snapshots.TwoBehaviors.Alpha,
                global::Skybeam.Tests.Snapshots.TwoBehaviors.Omega>,
            global::Skybeam.Tests.Snapshots.TwoBehaviors.BarHandler,
            global::FancyGlobalPrefix.Skybeam.Tests.Snapshots.TwoBehaviors.BarHandlerPipeline>();
    }
}
