using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;

using Skybeam.Abstractions;

// <auto-generated
namespace FancyGlobalPrefix.Skybeam.Tests.Snapshots.TwoBehaviors;

using InterfaceAlias = IRequestHandler<
    global::Skybeam.Tests.Snapshots.TwoBehaviors.Alpha,
    global::Skybeam.Tests.Snapshots.TwoBehaviors.Omega>;

using DelegateAlias = RequestHandlerDelegate<
    global::Skybeam.Tests.Snapshots.TwoBehaviors.Omega>;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Skybeam", "%VERSION%")]
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]

public class BarHandlerPipeline(IServiceProvider provider) : InterfaceAlias
{
    public Task<global::Skybeam.Tests.Snapshots.TwoBehaviors.Omega> HandleAsync(
        global::Skybeam.Tests.Snapshots.TwoBehaviors.Alpha input,
        CancellationToken ct = default)
    {
        var handler = provider.GetRequiredService<
            global::Skybeam.Tests.Snapshots.TwoBehaviors.BarHandler>(); 

        DelegateAlias original = () => handler.HandleAsync(input, ct);

        var b0 = provider.GetRequiredService<
            global::Skybeam.Tests.Snapshots.TwoBehaviors.LogBehavior<
                global::Skybeam.Tests.Snapshots.TwoBehaviors.Alpha,
                global::Skybeam.Tests.Snapshots.TwoBehaviors.Omega>>();

        DelegateAlias f0 = () => b0.HandleAsync(input, original, ct);

        var b1 = provider.GetRequiredService<
            global::Skybeam.Tests.Snapshots.TwoBehaviors.ExceptionBehavior<
                global::Skybeam.Tests.Snapshots.TwoBehaviors.Alpha,
                global::Skybeam.Tests.Snapshots.TwoBehaviors.Omega>>();

        DelegateAlias f1 = () => b1.HandleAsync(input, f0, ct);

        return f1();
    }
}