using System;
using Microsoft.Extensions.DependencyInjection;
using Skybeam.Abstractions;
using Skybeam;

// <auto-generated/>
namespace Tests.NestedHandler;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Skybeam", "%VERSION%")]
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]

public class PipelineRegistry : IPipelineRegistry
{
    public void Apply(IServiceCollection services)
    {
        services.ReplaceWithPipeline<
            IRequestHandler<
                global::Skybeam.Tests.Snapshots.NestedHandler.Alpha,
                global::Skybeam.Tests.Snapshots.NestedHandler.Omega>,
            global::Skybeam.Tests.Snapshots.NestedHandler.RootHandler,
            global::FancyGlobalPrefix.Skybeam.Tests.Snapshots.NestedHandler.RootHandlerPipeline>();
        
        services.ReplaceWithPipeline<
            IRequestHandler<
                global::Skybeam.Tests.Snapshots.NestedHandler.NestedAlpha,
                global::Skybeam.Tests.Snapshots.NestedHandler.NestedOmega>,
            global::Skybeam.Tests.Snapshots.NestedHandler.NestedHandler,
            global::FancyGlobalPrefix.Skybeam.Tests.Snapshots.NestedHandler.NestedHandlerPipeline>();
    }
}
