name: Publish Nuget Package

on:
  workflow_dispatch:
  push:
    tags: [ 'v*.*.*' ]

env:
  VERSION: 0.0.1-publish-yml

jobs:
  build-and-publish:
    permissions:
      contents: read
      id-token: write  # enable GitHub OIDC token issuance for this job

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/Skybeam
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Use the ambient GitHub token to login to NuGet and retrieve an API key
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Set Version Variable
        if: ${{ github.ref_type == 'tag' }}
        env:
          TAG: ${{ github.ref_name }}
        run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Retrieve file list
        run: ls

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release /p:Version=$VERSION

  #     - name: Test
  #       run: dotnet test --no-build --verbosity normal

      - name: Pack nuget packages
        run: |
            echo "Packing version $VERSION"
            dotnet pack --output nupkgs --no-restore --no-build -c Release /p:PackageVersion=$VERSION

      - name: Upload nuget packages
        if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
        run: dotnet nuget push nupkgs/*.nupkg -k ${{ steps.login.outputs.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json